<a href="https://colab.research.google.com/github/karur0su/-Note-Taker/blob/master/Building_Financial_Article_Category_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
import pandas as pd
import json
import pickle

In [5]:
 financial_corpus_df = pd.read_csv('training_data.csv')

In [6]:
financial_corpus_df

,id,category,title,body
0,5639,International_Finance,How Has Devaluation of the Yuan Impacted Globa...,How Has the Devaluation of the Yuan Impacted G...
1,2673,Earning_Reports,Qorvo® Announces Fiscal 2022 Third Quarter Fin...,"GREENSBORO, N.C., Feb. 02, 2022 (GLOBE NEWSWIR..."
2,2056,Commodities,Why Gatos Silver Stock Fell Another 15.5% at t...,Shares of Gatos Silver (NYSE:GATO) fell 15.5% ...
3,3455,Economy,Healthcare industry expects Budget 2022 to hik...,Healthcare industry expects Budget 2022 to hik...
4,4406,Fraud,American FX Fund CEO Sent to Jail for Running ...,The U.S Federal Bureau of Investigation (FBI) ...
...,...,...,...,...
8037,10024,Real_Estate,United Real Estate expands to Alabama with 2nd...,Dallas-based brokerage and franchisor United R...
8038,167,Capital,CTDOT Marks Transit Equity Day 2022 with Commi...,"(Newington, CT) - The Connecticut Department o..."
8039,2533,Earning_Reports,Lee Enterprises reports strong digital growth ...,Digital-only subscribers grew 57%; exceeds hal...
8040,5543,International_Finance,Fuel for Thought: Persian Gulf energy producer...,Geopolitics has jumped ahead of market fundame...
8041,2792,Earning_Reports,Tesla's entire year hinges on answering one bi...,Tesla reports second-quarter earnings on Wedne...

In [7]:
financial_corpus_df['category'].unique()

array(['International_Finance', 'Earning_Reports', 'Commodities',
       'Economy', 'Fraud', 'Mergers_Acquisitions', 'Policy', 'Oil',
       'Capital', 'Litigation', 'Real_Estate'], dtype=object)